set-option -g default-command "/bin/bash"

set -g allow-passthrough on
set -s extended-keys on

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"
set -as terminal-features ',xterm-256color:extkeys'

set -g mouse on
