// @vitest-environment jsdom
import { createRef } from 'react'
import { cleanup, fireEvent, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'

import ExitAlert from '../ExitAlert'

import {
  buildSurvey,
  installBrowserStubs,
  mockConfettiApi,
  renderWithTheme,
} from './confettiSurveyHarness'

vi.mock('../../AiBuilderContext', () => ({
  useAiBuilderContext: () => ({ chatId: 'chat-1' }),
}))

const RATING_QUESTION = 'How useful was the output generated by AI?'

function renderExitAlert() {
  const onExit = vi.fn()
  const onClose = vi.fn()

  renderWithTheme(
    <ExitAlert
      cancelRef={createRef<HTMLButtonElement>()}
      isOpen
      onClose={onClose}
      onExit={onExit}
    />,
  )

  return { onExit, onClose }
}

function requiredRatingSurvey() {
  return buildSurvey([
    {
      id: 'rating1',
      title: RATING_QUESTION,
      required: true,
      properties: { type: 'rating', scale: 5, display: 'star' },
    },
  ])
}

beforeEach(() => {
  installBrowserStubs()
})

afterEach(() => {
  cleanup()
  vi.unstubAllGlobals()
})

it('shows no validation error before the user tries to exit', async () => {
  mockConfettiApi({ survey: requiredRatingSurvey() })
  renderExitAlert()
  await screen.findByText(RATING_QUESTION)

  expect(screen.queryByText('This field is required')).toBeNull()
  expect(screen.queryByText('Invalid input')).toBeNull()
})

it('exits when the survey fails to load', async () => {
  mockConfettiApi({ failSurveyFetch: true })
  const { onExit, onClose } = renderExitAlert()
  await screen.findByRole('button', { name: 'Submit and exit' })

  fireEvent.click(screen.getByRole('button', { name: 'Submit and exit' }))

  await waitFor(() => expect(onExit).toHaveBeenCalledOnce())
  expect(onClose).toHaveBeenCalledOnce()
})

it('does not submit the survey when the user cancels', async () => {
  const api = mockConfettiApi({ survey: requiredRatingSurvey() })
  const { onExit, onClose } = renderExitAlert()
  await screen.findByText(RATING_QUESTION)

  fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))

  expect(api.submittedResponses()).toHaveLength(0)
  expect(onExit).not.toHaveBeenCalled()
  expect(onClose).toHaveBeenCalledOnce()
})
