// @vitest-environment jsdom
/**
 * Business rule: "Submit and exit" must respect the Confetti survey's
 * `required` setting. A required question that is unanswered keeps the user in
 * the AI builder, because users were skipping the survey and leaving.
 */
import { createRef } from 'react'
import { cleanup, fireEvent, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import ExitAlert from '../ExitAlert'

import {
  buildSurvey,
  installBrowserStubs,
  mockConfettiApi,
  renderWithTheme,
} from './confettiSurveyHarness'

vi.mock('../../AiBuilderContext', () => ({
  useAiBuilderContext: () => ({ chatId: 'chat-1' }),
}))

const RATING_QUESTION = 'How useful was the output generated by AI?'
const TEXT_QUESTION = 'How could it be better?'

function renderExitAlert() {
  const onExit = vi.fn()
  const onClose = vi.fn()

  renderWithTheme(
    <ExitAlert
      cancelRef={createRef<HTMLButtonElement>()}
      isOpen
      onClose={onClose}
      onExit={onExit}
    />,
  )

  return { onExit, onClose }
}

function clickSubmitAndExit() {
  fireEvent.click(screen.getByRole('button', { name: 'Submit and exit' }))
}

beforeEach(() => {
  installBrowserStubs()
})

afterEach(() => {
  cleanup()
  vi.unstubAllGlobals()
})

describe('required Confetti question', () => {
  it('keeps the user in the builder until the required question is answered', async () => {
    const api = mockConfettiApi({
      survey: buildSurvey([
        {
          id: 'rating1',
          title: RATING_QUESTION,
          required: true,
          properties: { type: 'rating', scale: 5, display: 'star' },
        },
        {
          id: 'text1',
          title: TEXT_QUESTION,
          required: false,
          properties: { type: 'open-ended', max: 1000 },
        },
      ]),
    })
    const { onExit, onClose } = renderExitAlert()
    await screen.findByText(RATING_QUESTION)

    clickSubmitAndExit()

    expect(onExit).not.toHaveBeenCalled()
    expect(onClose).not.toHaveBeenCalled()
    expect(api.submittedResponses()).toHaveLength(0)
    expect(await screen.findByText('This field is required')).toBeTruthy()

    fireEvent.click(screen.getAllByRole('radio')[4])
    clickSubmitAndExit()

    await waitFor(() => expect(api.submittedResponses()).toHaveLength(1))
    expect(api.submittedResponses()[0].body).toMatchObject({
      respondent: 'unknown-user-chat-1',
      data: { rating1: 5 },
    })
    expect(onExit).toHaveBeenCalledOnce()
    expect(onClose).toHaveBeenCalledOnce()
  })

  it('treats a whitespace-only answer to a required question as unanswered', async () => {
    const api = mockConfettiApi({
      survey: buildSurvey([
        {
          id: 'text1',
          title: TEXT_QUESTION,
          required: true,
          properties: { type: 'open-ended', max: 1000 },
        },
      ]),
    })
    const { onExit } = renderExitAlert()
    await screen.findByText(TEXT_QUESTION)

    fireEvent.change(screen.getByRole('textbox'), { target: { value: '   ' } })
    clickSubmitAndExit()

    expect(onExit).not.toHaveBeenCalled()
    expect(api.submittedResponses()).toHaveLength(0)

    fireEvent.change(screen.getByRole('textbox'), {
      target: { value: 'Needs fewer steps' },
    })
    clickSubmitAndExit()

    await waitFor(() => expect(api.submittedResponses()).toHaveLength(1))
    expect(api.submittedResponses()[0].body).toMatchObject({
      data: { text1: 'Needs fewer steps' },
    })
    expect(onExit).toHaveBeenCalledOnce()
  })

  it('exits straight away when every question is optional', async () => {
    const api = mockConfettiApi({
      survey: buildSurvey([
        {
          id: 'rating1',
          title: RATING_QUESTION,
          required: false,
          properties: { type: 'rating', scale: 5, display: 'star' },
        },
      ]),
    })
    const { onExit, onClose } = renderExitAlert()
    await screen.findByText(RATING_QUESTION)

    clickSubmitAndExit()

    await waitFor(() => expect(api.submittedResponses()).toHaveLength(1))
    expect(onExit).toHaveBeenCalledOnce()
    expect(onClose).toHaveBeenCalledOnce()
  })
})
