export const EDITOR_MARGIN_TOP_NUM = 61
export const EDITOR_MARGIN_TOP = `${EDITOR_MARGIN_TOP_NUM}px`
export const EDITOR_MAX_HEIGHT = `calc(100vh - ${EDITOR_MARGIN_TOP})`
export const EDITOR_RIGHT_DRAWER_WIDTH = '60%'
