export const REDIS_LOGICAL_DATABASES = 256
export const REDIS_DBS_PER_WORKER = 4
export const INTEGRATION_PROJECTS = 2
export const MAX_WORKER_SLOTS = Math.floor(
  REDIS_LOGICAL_DATABASES / REDIS_DBS_PER_WORKER / INTEGRATION_PROJECTS,
)
