import { useCallback, useMemo } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import type { UIMessage } from '@ai-sdk/react'
import { useChat } from '@ai-sdk/react'
import { useToast } from '@opengovsg/design-system-react'
import { DefaultChatTransport } from 'ai'

import * as URLS from '@/config/urls'
import { useAiBuilderContext } from '@/pages/AiBuilder/AiBuilderContext'
import {
  deduplicateMessages,
  extractTextContent,
  transformMessages,
} from '@/pages/AiBuilder/helpers'

export interface Message {
  id: string // this is auto-generated by the AI SDK
  text: string
  traceId?: string // only assistant messages have this
  isUser: boolean
}

// Custom message type with metadata
export type CustomUIMessage = UIMessage<{
  traceId?: string
}>

export interface UseChatStreamOptions {
  initialMessages?: Message[]
}

export function useChatStream(options: UseChatStreamOptions) {
  const toast = useToast()
  const navigate = useNavigate()
  const location = useLocation()
  const { ddSessionId } = useAiBuilderContext()

  const {
    messages: aiMessages,
    sendMessage,
    status,
    error: aiError,
    stop,
  } = useChat<CustomUIMessage>({
    transport: new DefaultChatTransport({
      api: '/api/chat',
      credentials: 'include',
      prepareSendMessagesRequest: ({ messages }) => {
        // Convert initialMessages to the format expected by the API
        const initialMsgs = (options?.initialMessages || []).map((msg) => ({
          id: msg.id,
          role: msg.isUser ? 'user' : 'assistant',
          parts: [{ type: 'text', text: msg.text }],
          ...(msg.traceId && { metadata: { traceId: msg.traceId } }),
        }))

        // Prepend initial messages to maintain full conversation context
        const allMessages = [...initialMsgs, ...messages]

        const body = {
          messages: allMessages,
          sessionId: ddSessionId,
        }
        return { body }
      },
    }),
    onError: (error: Error) => {
      toast({
        title: 'Error: ' + error.message,
        status: 'error',
        duration: 3000,
        isClosable: true,
        position: 'top',
      })
    },
    onFinish: ({ messages }) => {
      // transform the messages and save to location state
      // so that user can still access it if they refresh the page
      const transformedMessages = transformMessages(messages)

      // Combine initial messages with new messages to preserve full history
      const allMessages = deduplicateMessages([
        ...(options?.initialMessages || []),
        ...transformedMessages,
      ])

      navigate(`${URLS.EDITOR}/ai`, {
        state: {
          ...location.state,
          chatInput: allMessages[allMessages.length - 1].text,
          chatMessages: allMessages,
        },
        replace: true,
      })
    },
  })

  // Transform AI SDK messages to our Message format
  const messages = useMemo<Message[]>(() => {
    const isActivelyStreaming = status === 'streaming' || status === 'submitted'

    // Start with initial messages if provided
    const initialMsgs = options?.initialMessages || []

    // Filter user and assistant messages from AI SDK
    let messagesToTransform = aiMessages.filter(
      (msg) => msg.role === 'user' || msg.role === 'assistant',
    )

    // If streaming, exclude the last assistant message (shown via currentResponse)
    if (isActivelyStreaming && messagesToTransform.length > 0) {
      const lastMsg = messagesToTransform[messagesToTransform.length - 1]
      if (lastMsg.role === 'assistant') {
        messagesToTransform = messagesToTransform.slice(0, -1)
      }
    }

    const transformedMessages = transformMessages(messagesToTransform)
    const allMessages = deduplicateMessages([
      ...initialMsgs,
      ...transformedMessages,
    ])
    return allMessages
  }, [aiMessages, options?.initialMessages, status])

  // Get the current streaming response (last assistant message that's still being streamed)
  const currentResponse = useMemo(() => {
    const isActivelyStreaming = status === 'streaming' || status === 'submitted'

    if (!isActivelyStreaming) {
      return ''
    }

    const lastMessage = aiMessages[aiMessages.length - 1]
    if (lastMessage && lastMessage.role === 'assistant') {
      return extractTextContent(lastMessage)
    }
    return ''
  }, [aiMessages, status])

  // Wrapper for sendMessage that matches the expected signature
  const sendMessageWrapper = useCallback(
    (userPrompt: string) => {
      sendMessage({
        role: 'user',
        parts: [{ type: 'text', text: userPrompt }],
      })
    },
    [sendMessage],
  )

  return {
    messages,
    currentResponse,
    isStreaming: status === 'submitted' || status === 'streaming',
    error: aiError?.message || null,
    sendMessage: sendMessageWrapper,
    cancelStream: stop,
  }
}
