import { useCallback, useMemo, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import type { UIMessage } from '@ai-sdk/react'
import { useChat } from '@ai-sdk/react'
import { useToast } from '@opengovsg/design-system-react'
import { DefaultChatTransport } from 'ai'

import * as URLS from '@/config/urls'
import { useAiBuilderContext } from '@/pages/AiBuilder/AiBuilderContext'
import {
  deduplicateMessages,
  extractTextContent,
  transformMessages,
} from '@/pages/AiBuilder/helpers'

export interface Message {
  id: string // this is auto-generated by the AI SDK
  text: string
  traceId?: string // only assistant messages have this
  isUser: boolean
  /**
   * used to track the latest message with isChatReady: true.
   * this is used to determine where we should show the preview button
   * on mobile mode.
   * only assistant messages should have this.
   */
  isChatReady: boolean
}

// Custom message type with metadata
export type CustomUIMessage = UIMessage<{
  traceId?: string
}>

// Type for the step status data annotation
export type IsChatReadyPart = {
  type: 'data-isChatReady'
  data: {
    isChatReady: boolean
  }
}

export interface UseChatStreamOptions {
  initialMessages?: Message[]
}

export function useChatStream(options: UseChatStreamOptions) {
  const toast = useToast()
  const navigate = useNavigate()
  const location = useLocation()
  const { ddSessionId } = useAiBuilderContext()

  // Track step readiness from data-isChatReady annotation
  // Initialize based on whether initialMessages contains a ready message
  const initialIsReady = !!options?.initialMessages?.findLast(
    (msg) => msg.isChatReady,
  )
  const [isReady, setIsReady] = useState(initialIsReady)

  // Use ref to always access the latest location state in callbacks
  // This ensures onFinish sees updates made by other components (e.g., StepsPreview)
  const locationRef = useRef(location)
  locationRef.current = location

  const {
    messages: aiMessages,
    sendMessage,
    status,
    error: aiError,
    stop,
  } = useChat<CustomUIMessage>({
    transport: new DefaultChatTransport({
      api: '/api/chat',
      credentials: 'include',
      prepareSendMessagesRequest: ({ messages }) => {
        // Convert initialMessages to the format expected by the API
        const initialMsgs = (options?.initialMessages || []).map((msg) => ({
          id: msg.id,
          role: msg.isUser ? 'user' : 'assistant',
          parts: [{ type: 'text', text: msg.text }],
          ...(msg.traceId && { metadata: { traceId: msg.traceId } }),
        }))

        // Prepend initial messages to maintain full conversation context
        const allMessages = [...initialMsgs, ...messages]

        const body = {
          messages: allMessages,
          sessionId: ddSessionId,
        }
        return { body }
      },
    }),
    onError: (error: Error) => {
      toast({
        title: 'Error: ' + error.message,
        status: 'error',
        duration: 3000,
        isClosable: true,
        position: 'top',
      })
    },
    onFinish: ({ messages, isAbort }) => {
      // if the chat stream is cancelled, isAbort will be true
      if (isAbort) {
        return
      }

      // transform the messages and save to location state
      // so that user can still access it if they refresh the page
      const transformedMessages = transformMessages(messages)

      // Combine initial messages with new messages to preserve full history
      const allMessages = deduplicateMessages([
        ...(options?.initialMessages || []),
        ...transformedMessages,
      ])

      let isChatReady = false
      const lastMessage = messages[messages.length - 1]
      const isChatReadyPart = lastMessage.parts.find(
        (part): part is IsChatReadyPart => part.type === 'data-isChatReady',
      )
      if (isChatReadyPart) {
        isChatReady = isChatReadyPart.data.isChatReady
        setIsReady(isChatReady)
      }

      // Get current output from the ref (ensures we see latest state from other navigates)
      const currentOutput = locationRef.current.state?.output

      navigate(`${URLS.EDITOR}/ai`, {
        state: {
          ...locationRef.current.state,
          chatInput: allMessages[allMessages.length - 1].text,
          chatMessages: allMessages,
          // When isChatReady is true: clear output to trigger step generation
          ...(isChatReady
            ? { output: undefined }
            : // When isChatReady is false: preserve current output from ref
            currentOutput
            ? { output: currentOutput }
            : {}),
        },
        replace: true,
      })
    },
  })

  // Transform AI SDK messages to our Message format
  const messages = useMemo<Message[]>(() => {
    const isActivelyStreaming = status === 'streaming' || status === 'submitted'
    const initialMsgs = options?.initialMessages || []

    // Filter user and assistant messages from AI SDK
    let messagesToTransform = aiMessages.filter(
      (msg) => msg.role === 'user' || msg.role === 'assistant',
    )

    // If streaming, exclude the last assistant message (shown via currentResponse)
    if (isActivelyStreaming && messagesToTransform.length > 0) {
      const lastMsg = messagesToTransform[messagesToTransform.length - 1]
      if (lastMsg.role === 'assistant') {
        messagesToTransform = messagesToTransform.slice(0, -1)
      }
    }

    const transformedMessages = transformMessages(messagesToTransform)
    const combined = deduplicateMessages([
      ...initialMsgs,
      ...transformedMessages,
    ])

    // Ensure only the last message with isChatReady: true keeps the flag
    let lastReadyIndex = -1
    const allMessages = combined.map((msg, index) => {
      if (msg.isChatReady) {
        lastReadyIndex = index
      }
      return { ...msg, isChatReady: false }
    })

    if (lastReadyIndex !== -1) {
      allMessages[lastReadyIndex].isChatReady = true
    }

    return allMessages
  }, [aiMessages, options?.initialMessages, status])

  // Get the current streaming response (last assistant message that's still being streamed)
  const currentResponse = useMemo(() => {
    const isActivelyStreaming = status === 'streaming' || status === 'submitted'

    if (!isActivelyStreaming) {
      return ''
    }

    const lastMessage = aiMessages[aiMessages.length - 1]
    if (lastMessage && lastMessage.role === 'assistant') {
      return extractTextContent(lastMessage)
    }
    return ''
  }, [aiMessages, status])

  // Wrapper for sendMessage that matches the expected signature
  const sendMessageWrapper = useCallback(
    (userPrompt: string) => {
      // Reset isReady when sending a new message
      setIsReady(false)
      sendMessage({
        role: 'user',
        parts: [{ type: 'text', text: userPrompt }],
      })
    },
    [sendMessage],
  )

  return {
    messages,
    currentResponse,
    isStreaming: status === 'submitted' || status === 'streaming',
    isReady,
    error: aiError?.message || null,
    sendMessage: sendMessageWrapper,
    cancelStream: stop,
  }
}
