import type { IFlowSteps, IJSONObject } from '@plumber/types'

import { useCallback, useMemo, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import type { UIMessage } from '@ai-sdk/react'
import { useChat } from '@ai-sdk/react'
import { useToast } from '@opengovsg/design-system-react'
import { DefaultChatTransport } from 'ai'

import * as URLS from '@/config/urls'
import { useAiBuilderContext } from '@/pages/AiBuilder/AiBuilderContext'
import { MAX_MESSAGES } from '@/pages/AiBuilder/constants'
import {
  deduplicateMessages,
  extractTextContent,
  transformMessages,
} from '@/pages/AiBuilder/helpers'

export type DynamicPickerData =
  | { question: string; stepId: string; key: string }
  | { question: string; appKey: string }

export type DynamicPickerPart = {
  type: 'data-dynamicPicker'
  data: DynamicPickerData
}

export interface Message {
  id: string // this is auto-generated by the AI SDK
  text: string
  traceId?: string // only assistant messages have this
  isUser: boolean
  /**
   * used to track the latest message with isChatReady: true.
   * this is used to determine where we should show the preview button
   * on mobile mode.
   * only assistant messages should have this.
   */
  isChatReady: boolean
  clarification?: ClarificationPart['data']['questions']
  dynamicPicker?: DynamicPickerPart['data']
}

// Custom message type with metadata
export type CustomUIMessage = UIMessage<{
  traceId?: string
}>

// Type for the step status data annotation
export type IsChatReadyPart = {
  type: 'data-isChatReady'
  data: {
    isChatReady: boolean
    flowSteps?: IFlowSteps
    error?: string
    mcpMode?: boolean // true when mcpStepConfig LD flag is on — suppresses the create-pipe mutation button
  }
}

export type PipeStateStep = {
  id: string
  appKey: string
  key: string
  type: 'trigger' | 'action'
  position: number
  status: 'incomplete' | 'completed'
  parameters: Record<string, unknown>
  connectionId: string | null
  connectionLabel?: string | null
}

export type PipeStatePart = {
  type: 'data-pipeState'
  data: {
    pipeId: string
    steps: PipeStateStep[]
  }
}

export interface ClarificationQuestion {
  question: string
  options: string[]
}

// Type for clarification questions data annotation
export type ClarificationPart = {
  type: 'data-clarification'
  data: {
    questions: ClarificationQuestion[]
  }
}

export type StepUpdatePart = {
  type: 'data-stepUpdate'
  data: {
    stepId: string
    parameters: IJSONObject
    parameterLabels?: Record<string, string>
  }
}

export interface UseChatStreamOptions {
  initialMessages?: Message[]
}

export function useChatStream(options: UseChatStreamOptions) {
  const toast = useToast()
  const navigate = useNavigate()
  const location = useLocation()
  const { ddSessionId, output, refetchTestExecutionSteps } =
    useAiBuilderContext()

  // Use ref to always access the latest pipe output in prepareSendMessagesRequest
  const outputRef = useRef(output)
  outputRef.current = output

  // useChat captures onFinish on mount, so without a ref this would call a
  // stale refetch function tied to whatever query instance existed at mount.
  const refetchTestExecutionStepsRef = useRef(refetchTestExecutionSteps)
  refetchTestExecutionStepsRef.current = refetchTestExecutionSteps

  // After a refresh, chatMessages (persisted, text-only) is all that's left of
  // the conversation — every tool result and data-pipeState part (the only
  // places real step IDs ever appeared) is gone. Without this, the model has
  // no ground truth for step IDs on its first post-refresh turn and guesses.
  // Fires once per mount only — after that, the live conversation carries its
  // own tool-call history forward same as before.
  const hasSentPipeContextRef = useRef(false)

  // Track step readiness from data-isChatReady annotation
  // Initialize based on whether initialMessages contains a ready message.
  // Lazy initializer avoids re-running findLast on every render (useState only
  // uses the initial value on mount).
  const [isReady, setIsReady] = useState(
    () => !!options?.initialMessages?.findLast((msg) => msg.isChatReady),
  )

  // Use ref to always access the latest location state in callbacks
  // This ensures onFinish sees updates made by other components (e.g., StepsPreview)
  const locationRef = useRef(location)
  locationRef.current = location

  // Use ref to always access the latest initialMessages in callbacks.
  // useChat captures its transport/onFinish on mount, so without a ref,
  // prepareSendMessagesRequest and onFinish would use stale initialMessages
  // (e.g. the old 50 messages after clicking "New Chat").
  const initialMessagesRef = useRef(options?.initialMessages)
  initialMessagesRef.current = options?.initialMessages

  const {
    messages: aiMessages,
    sendMessage,
    setMessages,
    status,
    error: aiError,
    stop,
  } = useChat<CustomUIMessage>({
    transport: new DefaultChatTransport({
      api: '/api/chat',
      credentials: 'include',
      prepareSendMessagesRequest: ({ messages }) => {
        // Filter out any initialMessages already tracked by the AI SDK to avoid
        // duplicates (the SDK accumulates messages across exchanges in its own state)
        const aiMessageIds = new Set(messages.map((m) => m.id))
        const initialMsgs = (initialMessagesRef.current || [])
          .filter((msg) => !aiMessageIds.has(msg.id))
          .map((msg) => ({
            id: msg.id,
            role: msg.isUser ? 'user' : 'assistant',
            parts: [{ type: 'text', text: msg.text }],
            ...(msg.traceId && { metadata: { traceId: msg.traceId } }),
          }))

        // First request since mount: if a pipe already has real step IDs
        // (data-pipeState survived in the persisted draft) but this mount's
        // own conversation history doesn't carry them (post-refresh), resync
        // the model with just the ID mapping it needs — not the full step
        // config — so it doesn't have to guess a step_id for tool calls like
        // get_dynamic_data.
        const pipeContextMsgs = []
        if (!hasSentPipeContextRef.current) {
          hasSentPipeContextRef.current = true
          const currentSteps = outputRef.current?.pipeId
            ? outputRef.current?.steps
            : undefined
          const configuredSteps = Array.isArray(currentSteps)
            ? currentSteps.filter(
                (s: { appKey?: string; key?: string }) => s.appKey && s.key,
              )
            : []
          if (configuredSteps.length > 0) {
            const stepIdMapping = configuredSteps
              .map(
                (
                  s: { id: string; appKey: string; key: string; type: string },
                  i: number,
                ) => `${i + 1}. ${s.appKey}/${s.key} (${s.type}) — id: ${s.id}`,
              )
              .join('\n')
            pipeContextMsgs.push({
              id: 'pipe-context-resync',
              role: 'assistant' as const,
              parts: [
                {
                  type: 'text' as const,
                  text: `[Internal resync — do not mention this to the user] Current pipe steps and their real IDs, for use as step_id in tool calls:\n${stepIdMapping}`,
                },
              ],
            })
          }
        }

        // Prepend initial messages to maintain full conversation context.
        // Filter out assistant messages with no text content — these can be left
        // behind when the user stops the stream before any output is produced,
        // and would fail backend schema validation.
        const allMessages = [
          ...initialMsgs,
          ...pipeContextMsgs,
          ...messages,
        ].filter((msg) => {
          if (msg.role !== 'assistant') {
            return true
          }
          return (msg.parts ?? []).some(
            (part) =>
              part.type === 'text' &&
              !!(part as { type: string; text?: string }).text?.trim(),
          )
        })

        const body = {
          messages: allMessages,
          sessionId: ddSessionId,
        }
        return { body }
      },
    }),
    onError: (error: Error) => {
      toast({
        title: 'Error: ' + error.message,
        status: 'error',
        duration: 3000,
        isClosable: true,
        position: 'top',
      })
    },
    onFinish: ({ messages, isAbort }) => {
      // if the chat stream is cancelled, isAbort will be true
      if (isAbort) {
        return
      }

      // transform the messages and save to location state
      // so that user can still access it if they refresh the page
      const transformedMessages = transformMessages(messages)

      // Combine initial messages with new messages to preserve full history
      const allMessages = deduplicateMessages([
        ...(initialMessagesRef.current || []),
        ...transformedMessages,
      ])

      const lastMessage = messages[messages.length - 1]

      // Phase 2b+: DB-backed pipe state from data-pipeState event
      const pipeStatePart = lastMessage.parts.find(
        (part): part is PipeStatePart => part.type === 'data-pipeState',
      )

      // Phase 2a or old path: workflow proposal from data-isChatReady event
      const isChatReadyPart = lastMessage.parts.find(
        (part): part is IsChatReadyPart => part.type === 'data-isChatReady',
      )

      const { isChatReady, flowSteps, error, mcpMode } =
        isChatReadyPart?.data ?? {}

      if (pipeStatePart || isChatReady) {
        setIsReady(true)
      }

      // A step may have just been test-executed via the execute_step tool
      // this turn — refetch so newly-available dataOutMetadata labels show
      // up in variable pills without needing a page refresh. Best-effort:
      // a failed refetch just leaves labels/values on their naive fallback.
      //
      // NOTE: this fires unconditionally every finished turn (not just ones
      // where a step was actually executed), since precisely detecting an
      // execute_step tool call requires reading AI SDK tool-* parts, which
      // is unprecedented and type-unsafe in this codebase today (no shared
      // type for the tool's output, no compile-time check on the state
      // string). Revisit if turn volume or this query's cost ever becomes
      // a real concern — see execute-step tool part detection discussion.
      if (outputRef.current?.pipeId) {
        refetchTestExecutionStepsRef.current().catch(() => {
          // no-op: naive label/value fallback is an acceptable outcome
        })
      }

      // Get current output from the ref (ensures we see latest state from other navigates)
      const currentOutput = locationRef.current.state?.output

      // Accumulate parameter labels alongside the rest of the draft (never
      // persisted server-side) so they survive a refresh in lockstep with
      // chatMessages/output instead of drifting via a separate store.
      const previousParameterLabels: Record<
        string,
        Record<string, string>
      > = locationRef.current.state?.parameterLabelsByStepId ?? {}
      const parameterLabelsByStepId = { ...previousParameterLabels }
      for (const part of lastMessage.parts ?? []) {
        if (part.type === 'data-stepUpdate') {
          const { stepId, parameterLabels } = (part as StepUpdatePart).data
          if (parameterLabels) {
            parameterLabelsByStepId[stepId] = {
              ...parameterLabelsByStepId[stepId],
              ...parameterLabels,
            }
          }
        }
      }

      navigate(`${URLS.EDITOR}/ai`, {
        state: {
          ...locationRef.current.state,
          chatInput: allMessages[allMessages.length - 1].text,
          chatMessages: allMessages,
          parameterLabelsByStepId,
          // pipeStatePart: replace output with DB pipe state (Phase 2b+)
          // isChatReady: populate output from stream (steps or error), drawer opens
          // neither: preserve current output
          ...(pipeStatePart
            ? { output: pipeStatePart.data }
            : isChatReady
            ? {
                output: {
                  ...(flowSteps ?? { error }),
                  mcpMode: mcpMode ?? false,
                },
                ...(flowSteps?.name ? { flowName: flowSteps.name } : {}),
              }
            : currentOutput
            ? { output: currentOutput }
            : {}),
        },
        replace: true,
      })
    },
  })

  // Transform AI SDK messages to our Message format.
  // Uses options?.initialMessages directly (not the ref) so the memo re-runs
  // reactively when initialMessages changes (e.g., after "New Chat").
  const messages = useMemo<Message[]>(() => {
    const isActivelyStreaming = status === 'streaming' || status === 'submitted'
    const initialMsgs = options?.initialMessages || []

    // Filter user and assistant messages from AI SDK
    let messagesToTransform = aiMessages.filter(
      (msg) => msg.role === 'user' || msg.role === 'assistant',
    )

    // If streaming, exclude the last assistant message (shown via currentResponse)
    if (isActivelyStreaming && messagesToTransform.length > 0) {
      const lastMsg = messagesToTransform[messagesToTransform.length - 1]
      if (lastMsg.role === 'assistant') {
        messagesToTransform = messagesToTransform.slice(0, -1)
      }
    }

    // Filter out assistant messages with no text content — these are left behind
    // when the user stops the stream before any output is produced
    messagesToTransform = messagesToTransform.filter(
      (msg) =>
        msg.role !== 'assistant' || extractTextContent(msg).trim().length > 0,
    )

    const transformedMessages = transformMessages(messagesToTransform)
    const combined = deduplicateMessages([
      ...initialMsgs,
      ...transformedMessages,
    ])

    // Ensure only the last message with isChatReady: true keeps the flag
    let lastReadyIndex = -1
    const allMessages = combined.map((msg, index) => {
      if (msg.isChatReady) {
        lastReadyIndex = index
      }
      return { ...msg, isChatReady: false }
    })

    if (lastReadyIndex !== -1) {
      allMessages[lastReadyIndex].isChatReady = true
    }

    return allMessages
  }, [aiMessages, options?.initialMessages, status])

  // Get the current streaming response (last assistant message that's still being streamed)
  const currentResponse = useMemo(() => {
    const isActivelyStreaming = status === 'streaming' || status === 'submitted'

    if (!isActivelyStreaming) {
      return ''
    }

    const lastMessage = aiMessages[aiMessages.length - 1]
    if (lastMessage && lastMessage.role === 'assistant') {
      return extractTextContent(lastMessage)
    }
    return ''
  }, [aiMessages, status])

  const {
    stepParametersByStepId,
    parameterLabelsByStepId,
    activeStepId,
    completedStepIds,
  } = useMemo(() => {
    const byStepId: Record<string, IJSONObject> = {}
    const labelsByStepId: Record<string, Record<string, string>> = {}
    let latestStepId: string | null = null
    const completed = new Set<string>()

    for (const msg of aiMessages) {
      if (msg.role !== 'assistant') {
        continue
      }
      for (const part of msg.parts ?? []) {
        if (part.type === 'data-stepUpdate') {
          const { stepId, parameters, parameterLabels } = (
            part as StepUpdatePart
          ).data
          byStepId[stepId] = parameters
          if (parameterLabels) {
            labelsByStepId[stepId] = parameterLabels
          }
          latestStepId = stepId
        }
        if (part.type === 'data-pipeState') {
          for (const step of (part as PipeStatePart).data.steps) {
            if (step.status === 'completed') {
              completed.add(step.id)
            }
          }
        }
      }
    }

    return {
      stepParametersByStepId: byStepId,
      parameterLabelsByStepId: labelsByStepId,
      activeStepId: latestStepId,
      completedStepIds: completed,
    }
  }, [aiMessages])

  const resetChat = useCallback(() => {
    setMessages([])
    setIsReady(false)
  }, [setMessages])

  // Wrapper for sendMessage that matches the expected signature
  const sendMessageWrapper = useCallback(
    (userPrompt: string) => {
      // Reset isReady when sending a new message
      setIsReady(false)
      sendMessage({
        role: 'user',
        parts: [{ type: 'text', text: userPrompt }],
      })
    },
    [sendMessage],
  )

  return {
    messages,
    currentResponse,
    isStreaming: status === 'submitted' || status === 'streaming',
    isReady,
    error: aiError?.message || null,
    sendMessage: sendMessageWrapper,
    cancelStream: stop,
    resetChat,
    hasReachedLimit: messages.length >= MAX_MESSAGES,
    activeStepId,
    stepParametersByStepId,
    parameterLabelsByStepId,
    completedStepIds,
  }
}
