version: '3'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=plumber_dev
    ports:
      - 5432:5432
    volumes:
      - plumber-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:6.2.0-alpine
    ports:
      - 6379:6379
    volumes:
      - plumber-redis:/var/lib/redis/
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-username
      - MINIO_ROOT_PASSWORD=minio-password
      - MINIO_SITE_REGION=ap-southeast-1
    volumes:
      - plumber-minio:/data
  create-minio-buckets:
    image: bitnami/minio-client:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/bash -c "
      /usr/bin/env mc config host add plumber-minio http://minio:9000 minio-username minio-password &&
      /usr/bin/env mc mb --ignore-existing plumber-minio/plumber-development-common-bucket 
      "
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    user: root
    environment:
      REGION: 'ap-southeast-1'
    volumes:
      - plumber-dynamodb:/home/dynamodblocal/data
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data'

volumes:
  plumber-postgres:
  plumber-redis:
  plumber-minio:
  plumber-dynamodb:
