version: '3'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=plumber_dev
    ports:
      - 5432:5432
    volumes:
      - plumber-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:6.2.0-alpine
    ports:
      - 6379:6379
    volumes:
      - plumber-redis:/var/lib/redis/
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-username
      - MINIO_ROOT_PASSWORD=minio-password
    volumes:
      - plumber-minio:/data
volumes:
  plumber-postgres:
  plumber-redis:
  plumber-minio:
