name: Deploy to staging

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging-v2

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'staging'
      aws-account-id: '964715690079'
      cicd-role: 'arn:aws:iam::964715690079:role/plumber-staging-github-oidc-role'
      ecr-repository: 'plumber-staging'
      ecs-cluster-name: 'plumber-staging-ecs'
      ecs-service-name: 'plumber-staging-ecs-service'
      codedeploy-application: 'plumber-staging-ecs-app'
      codedeploy-deployment-group: 'plumber-staging-ecs-dg'
      release-version: ${{ github.sha }}
