name: Test and build

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          npm-taskforcesh-token: ${{ secrets.NPM_TASKFORCESH_TOKEN }}
      - run: pnpm run lint
      - run: echo "✅ Lint check passed."

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          npm-taskforcesh-token: ${{ secrets.NPM_TASKFORCESH_TOKEN }}
      - run: pnpm run typecheck
      - run: echo "✅ Typecheck passed."

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          npm-taskforcesh-token: ${{ secrets.NPM_TASKFORCESH_TOKEN }}
      - run: VITE_MODE=test pnpm run build
      - run: echo "✅ Build check passed."

  test-backend-unit:
    name: Test (backend unit)
    runs-on: ubuntu-latest
    timeout-minutes: 24
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          npm-taskforcesh-token: ${{ secrets.NPM_TASKFORCESH_TOKEN }}
      - name: Configure Datadog Test Visibility
        env:
          DD_SERVICE_NAME: ${{ secrets.DD_SERVICE_NAME }}
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: ${{ secrets.DD_SERVICE_NAME }}
          api_key: ${{ secrets.DD_API_KEY }}
          # we need to pin this for now since 5.68.0 breaks the ci
          js-tracer-version: 5.67.0
      - run: pnpm exec turbo run test:unit --filter=backend
        env:
          # Required to allow Datadog to trace Vitest tests
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}
      - run: echo "✅ Backend unit tests passed."

  test-backend-integration:
    name: Test (backend integration)
    runs-on: ubuntu-latest
    timeout-minutes: 24
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          npm-taskforcesh-token: ${{ secrets.NPM_TASKFORCESH_TOKEN }}
      - name: Configure Datadog Test Visibility
        env:
          DD_SERVICE_NAME: ${{ secrets.DD_SERVICE_NAME }}
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: ${{ secrets.DD_SERVICE_NAME }}
          api_key: ${{ secrets.DD_API_KEY }}
          # we need to pin this for now since 5.68.0 breaks the ci
          js-tracer-version: 5.67.0
      - run: pnpm exec turbo run test:integration --filter=backend
        env:
          # Required to allow Datadog to trace Vitest tests
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}
      - run: echo "✅ Backend integration tests passed."

  test-frontend:
    name: Test (frontend)
    runs-on: ubuntu-latest
    timeout-minutes: 24
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          npm-taskforcesh-token: ${{ secrets.NPM_TASKFORCESH_TOKEN }}
      - name: Configure Datadog Test Visibility
        env:
          DD_SERVICE_NAME: ${{ secrets.DD_SERVICE_NAME }}
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: ${{ secrets.DD_SERVICE_NAME }}
          api_key: ${{ secrets.DD_API_KEY }}
          # we need to pin this for now since 5.68.0 breaks the ci
          js-tracer-version: 5.67.0
      - run: pnpm exec turbo run test --filter=frontend
        env:
          # Required to allow Datadog to trace Vitest tests
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}
      - run: echo "✅ Frontend tests passed."
